name: Metrics
on:
  schedule: [{ cron: "0 16 * * *" }]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Default metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_renders/metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_renders/metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5

      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_renders/metrics.plugin.topics.icons.svg
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons

