name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Default metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_renders/metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_renders/metrics.plugin.leetcode.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
