name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: /metrics_renders/metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
